#!/bin/sh
#
# An example hook script to prepare a packed repository for use over
# dumb transports.
#
# To enable this hook, rename this file to "post-update".

# exec git update-server-info

# sourcetree_gitflow_Multi-Version-Concurrency
# master_qq,master_sina
# develop_qq,develop_sina
# feature/_qq_feature1
# hotfix/_qq_hotfix1
# create by woolge,Email:917595913@qq.com

#the function get_curent_branch
get_curent_branch(){
	# get the current branch
	current_branch=$(git branch | sed -e '/^[^*]/d' | sed -e 's/\s//g')
	current_branch=${current_branch:1}
}

#the function of select_gitflow_branch
select_gitflow_branch(){
	# get the current branch
	get_curent_branch
	current_branch_rel=`echo $current_branch|cut -d "/" -f2` 
	version=`echo $current_branch_rel|cut -d "_" -f2` 

	master_tem="master_${version}"
	master_tem_branch=$(git branch | sed -e 's/\s//g' | sed -e "/$master_tem/!d")
	if [ "$master_tem_branch" != "" ]  
	then  
	    gitflow_branch_master=$master_tem
	else  
	    gitflow_branch_master="master"
	fi  

	develop_tem="develop_${version}"
	develop_tem_branch=$(git branch | sed -e 's/\s//g' | sed -e "/$develop_tem/!d")
	if [ "$develop_tem_branch" != "" ]  
	then  
	    gitflow_branch_develop=$develop_tem
	else  
	    gitflow_branch_develop="develop"
	fi  

}

# the fucntion of replace_gitflow_branch
replace_gitflow_branch(){
	config=$(pwd)"/.git/config"
	select_gitflow_branch

	# sed -i "10c master = $gitflow_branch_master" $config
	# sed -i "11c develop = $gitflow_branch_develop" $config

	master_line=$(sed -e '/^\tmaster\s=\s/!d' $config | sed -e 's/\t//g')
	develop_line=$(sed -e '/^\tdevelop\s=\s/!d' $config | sed -e 's/\t//g')
	sed -i "s/$master_line/master = $gitflow_branch_master/" $config
	sed -i "s/$develop_line/develop = $gitflow_branch_develop/" $config
}

# using replace_gitflow_branch
# replace_gitflow_branch
# echo -e "---you are using sourcetree_gitflow_Multi-Version-Concurrency---\n"

# using replace_gitflow_branch
config=$(pwd)"/.git/config"
gitflow=$(sed -e '/\[gitflow "branch"\]/!d' "$config")
if [ "$gitflow" != "" ]; then
	# echo "It is gitflow"
	replace_gitflow_branch
	echo -e "---you are using sourcetree_gitflow_Multi-Version-Concurrency---\n"
else  
    echo "Use gitflow,please."
fi